[workspace]
resolver = "3"
members = ["neorv32-pac", "embassy-neorv32"]
exclude = ["embassy-neorv32/examples"]

[workspace.package]
version = "0.1.0"
edition = "2024"
repository = "https://github.com/kurtjd/neorv32-rs"
