[alias]
# Run examples
run-sim = "run --config .cargo/runner.sim.toml --no-default-features --features single-core,sim"
run-fpga = "run --config .cargo/runner.fpga.toml --no-default-features --features single-core,fpga"
run-dc-sim = "run --config .cargo/runner.sim.toml --no-default-features --features dual-core,sim"
run-dc-fpga = "run --config .cargo/runner.fpga.toml --no-default-features --features dual-core,fpga"

# Build examples
build-sim = "build --no-default-features --features single-core,sim"
build-fpga = "build --no-default-features --features single-core,fpga"
build-dc-sim = "build --no-default-features --features dual-core,sim"
build-dc-fpga = "build --no-default-features --features dual-core,fpga"

# Report binary size of examples
size-sim = "size --no-default-features --features single-core,sim,"
size-fpga = "size --no-default-features --features single-core,fpga"
size-dc-sim = "size --no-default-features --features dual-core,sim,"
size-dc-fpga = "size --no-default-features --features dual-core,fpga"

# Display symbols of examples
nm-sim = "nm --no-default-features --features single-core,sim,"
nm-fpga = "nm --no-default-features --features single-core,fpga"
nm-dc-sim = "nm --no-default-features --features dual-core,sim,"
nm-dc-fpga = "nm --no-default-features --features dual-core,fpga"

# Perform objdump on examples
objdump-sim = "objdump --no-default-features --features single-core,sim,"
objdump-fpga = "objdump --no-default-features --features single-core,fpga"
objdump-dc-sim = "objdump --no-default-features --features dual-core,sim,"
objdump-dc-fpga = "objdump --no-default-features --features dual-core,fpga"

# Target can be modified depending on which extensions your NEORV32 config supports
[build]
target = "riscv32imc-unknown-none-elf"
rustflags = ["-C", "link-arg=-Tlink.x"]
